# Generated by Django 3.2.13 on 2023-05-08 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='rfp_bk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfp_name', models.CharField(max_length=200)),
                ('question', models.CharField(max_length=2048)),
                ('topic', models.CharField(max_length=100)),
                ('answer', models.CharField(max_length=2048)),
                ('winLoss', models.BooleanField()),
                ('comply', models.BooleanField()),
            ],
        ),
    ]
