# Generated by Django 4.2.1 on 2023-05-11 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfp_kb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfp_bk',
            name='product',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rfp_bk',
            name='product_variant',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
